#!/usr/bin/env bash

idir="$HOME/.config/bspwm/.bspwm"
source $idir

case $MUSIC in
	on)
		$NOTIFIER -r 13 -i "$ICONDIR/media-playpause.png" -t 1500 -u low "Music" "Stop"
		sed -i '6s_.*_MUSIC="off"_' $idir
		killall mpd; killall ncmpcpp
		;;
	off)
		$NOTIFIER -r 13 -i "$ICONDIR/media-playpause.png" -t 1500 -u low "Music" "Play"
		sed -i '6s_.*_MUSIC="on"_' $idir
		mpd; urxvt -name 'music' -e ncmpcpp
		;;
	*)
		sed -i '6s_.*_MUSIC="off"_' $idir
		killall mpd; killall ncmpcpp
		;;
esac

&> /dev/null
exit
