#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

# config
bspc config border_width         0
bspc config window_gap           7
bspc config split_ratio          0
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer	true

# rule
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a URxvt state=floating
bspc rule -a URxvt:music desktop='^5'
bspc rule -a Viewnior state=floating

# scripts
~/.config/bspwm/startup &
~/.config/bspwm/scripts/display/brightness-startup &> /dev/null &

# app
killall dunst &
lxpolkit &
xsetroot -cursor_name left_ptr &
xfce4-power-manager &
pkill picom; picom -b & 

